// MIT License (see LICENSE.md) Copyright (c) 2018 Trevor Sundberg
#pragma once
#include "ne_core.h"

#include "ne_clipboard.h"
#include "ne_core.h"
#include "ne_cpu.h"
#include "ne_debug.h"
#include "ne_file.h"
#include "ne_filesystem.h"
#include "ne_io.h"
#include "ne_keyboard.h"
#include "ne_memory.h"
#include "ne_mouse.h"
#include "ne_package.h"
#include "ne_power.h"
#include "ne_sandbox.h"
#include "ne_socket.h"
#include "ne_thread.h"
#include "ne_timer.h"
#include "ne_touch.h"
#include "ne_version.h"
#include "ne_vulkan.h"

// These are APIs that are planned:
//#include "ne_atomic.h"
//#include "ne_audio.h"
//#include "ne_event.h"
//#include "ne_gamepad.h"
//#include "ne_haptic.h"
//#include "ne_intrinsic.h"
//#include "ne_joystick.h"
//#include "ne_port.h"
//#include "ne_print.h"
//#include "ne_window.h"
